
import styles from './TutorialModal.module.css';
import { useGame } from '../../app/GameProvider';

export function TutorialModal() {
    const { dismissTutorial } = useGame();

    return (
        <div className={styles.overlay}>
            <div className={styles.modal}>
                <header className={styles.header}>
                    <h2>Welcome, Incubator</h2>
                    <p>Briefing Protocol v1.0</p>
                </header>

                <div className={styles.content}>
                    <section className={styles.section}>
                        <h3>🛠 The Goal</h3>
                        <p>
                            <strong>Win the election.</strong> You need <strong>6 Delegates</strong> to secure a majority.
                            Delegates are ONLY generated by <strong>Federations</strong>.
                            Individual unions do NOT vote.
                        </p>
                    </section>

                    <section className={styles.section}>
                        <h3>🔄 The Cycle</h3>
                        <p>
                            1. <strong>Generate</strong> empty unions.<br />
                            2. <strong>License & Incubate</strong> them to make them "real".<br />
                            3. <strong>Federate</strong> 2 licensed unions into a Federation.<br />
                            4. Each Federation yields <strong>2 Delegates</strong> forever.
                        </p>
                    </section>

                    <section className={`${styles.section} ${styles.warning}`}>
                        <h3>⚠️ Risks</h3>
                        <p>
                            Don't run out of <strong>Legitimacy</strong>.<br />
                            Keep <strong>Audit Risk</strong> low (creating federations raises it).<br />
                            Don't let <strong>Street Heat</strong> hit 100% or we get shut down.
                        </p>
                    </section>
                </div>

                <footer className={styles.footer}>
                    <button className={styles.button} onClick={dismissTutorial}>
                        I Understand. Let's Work.
                    </button>
                </footer>
            </div>
        </div>
    );
}
